// Generated by LiveScript 1.3.0
(function(){
  var chainCtrl, toIndex, myHash, myDummy, myGoban;
  chainCtrl = function($scope, $colMax, $dummy, $goban, $timeout){
    var res$, i$, ridx$;
    res$ = [];
    for (i$ = 0; i$ <= $colMax; ++i$) {
      ridx$ = i$;
      res$.push(ridx$);
    }
    $scope.myColumnIndex = res$;
    $scope.myFolderIndex = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    $scope.backup = function(){
      var i$, ref$, len$, i;
      for (i$ = 0, len$ = (ref$ = $scope.myFolderIndex).length; i$ < len$; ++i$) {
        i = ref$[i$];
        window.open($path + $title + i + '.csv', '_blank', "width=0, height=0, titlebar=no, toolbar=no");
      }
    };
    $scope.goban = $goban;
    $scope.goban.data = $dummy;
    $scope.goban.load($goban.myI);
    window.uploadDone = function(){
      alert('ha');
    };
  };
  toIndex = function(){
    return function(list){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = list.length - 1; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    };
  };
  myHash = function(){
    return {
      data: location.hash,
      asArray: function(){
        return this.data.replace('#', '').split('&');
      },
      upDateFromArray: function(list){
        location.hash = '#' + list.join('&');
      }
    };
  };
  myDummy = {
    name: '赤皮仔',
    isFolder: false,
    url: 'https://autolearn.hackpad.com/33EfKKhNtF8'
  };
  myGoban = function($http, $sce, $path, $title, $hash, $timeout){
    var goban, parseFromCSV;
    goban = new Object;
    parseFromCSV = function(csv){
      var allTextLines, bodyLines, goodList, lastFolder, bestList;
      allTextLines = csv.split(/\r\n|\n/);
      bodyLines = allTextLines.slice(2);
      goodList = bodyLines.map(function(text){
        return text.split(',');
      }).filter(function(list){
        return list[1];
      });
      lastFolder = {
        id: 0,
        set: function(n){
          this.id = n;
        }
      };
      bestList = goodList.map(function(list, index){
        var isClosed, obj;
        isClosed = false;
        if (!list[0]) {
          lastFolder.set(index);
          if (list[2] && list[2].search(/expand(.+)true/ > -1)) {
            isClosed = true;
          }
        }
        obj = (list[0] && {
          url: list[0].replace(/["\s]/g, ''),
          name: list[1].replace(/["\s]/g, ''),
          isFolder: false,
          pIndex: lastFolder.id
        }) || {
          name: list[1],
          isFolder: true,
          isClosed: isClosed
        };
        return obj;
      });
      return bestList;
    };
    goban.path = $path || '';
    goban.title = $hash.asArray()[0] || $title;
    goban.myI = $hash.asArray()[1] || 0;
    goban.myJ = $hash.asArray()[2] || 0;
    goban.pageLoading = false;
    goban.setI = function(n){
      if (goban.myI !== n) {
        goban.loadPage();
        $timeout(function(){
          goban.myI = n;
          goban.updateHash();
          goban.load(goban.myI);
        }, 1000);
      }
    };
    goban.setJ = function(n){
      if (goban.myJ !== n) {
        goban.loadPage();
        $timeout(function(){
          goban.myJ = n;
          goban.updateHash();
        }, 1000);
      }
    };
    goban.loadPage = function(){
      goban.pageLoading = true;
      $timeout(function(){
        goban.pageLoading = false;
      }, 2300);
    };
    goban.updateHash = function(){
      $hash.upDateFromArray([goban.title, goban.myI, goban.myJ]);
    };
    goban.load = function(num){
      $http({
        method: "GET",
        url: $path + $title + num + '.csv',
        dataType: "text"
      }).success(function(data){
        return goban.data = parseFromCSV(data);
      });
    };
    goban.keyDown = function($event){
      var code;
      console.log($event);
      $event.preventDefault();
      code = $event.keyCode;
      if (code === 40) {
        goban.up(1);
      }
      if (code === 38) {
        goban.up(-1);
      }
      if (code === 37) {
        goban.left(-1);
      }
      if (code === 39) {
        goban.left(1);
      }
      if (code === 32) {
        goban.data[goban.myJ].isClosed = !goban.data[goban.myJ].isClosed;
      }
    };
    goban.left = function(n){
      goban.loadPage();
      goban.load(parseInt(goban.myI) + n);
      $timeout(function(){
        goban.myI = parseInt(goban.myI);
        goban.myI += n;
        if (goban.myI === -1) {
          goban.myI = $colMax;
        }
        if (goban.myI === $colMax + 1) {
          goban.myI = 0;
        }
        goban.updateHash();
      }, 1000);
    };
    goban.up = function(n){
      goban.loadPage();
      $timeout(function(){
        goban.myJ = parseInt(goban.myJ);
        goban.myJ += n;
        if (goban.myJ === -1) {
          goban.myJ = goban.data.length - 1;
        }
        if (goban.myJ === goban.data.length) {
          goban.myJ = 0;
        }
        goban.updateHash();
      }, 1000);
    };
    goban.trust = function(url){
      return $sce.trustAsResourceUrl(url);
    };
    goban.getCurrentURL = function(){
      return goban.trust(goban.data[goban.myJ].url || goban.data[goban.myJ + 1].url);
    };
    return goban;
  };
  angular.module('goban', []).factory('$hash', myHash).factory('$goban', ['$http', '$sce', '$path', '$title', '$hash', '$timeout', myGoban]).filter('toIndex', toIndex);
}).call(this);
