// Generated by LiveScript 1.3.0
(function(){
  var toIndex, myHash, myGoban;
  toIndex = function(){
    return function(list){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = list.length - 1; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    };
  };
  myHash = function(){
    return {
      data: location.hash,
      asArray: function(){
        return this.data.replace('#', '').split('&');
      },
      upDateFromArray: function(list){
        location.hash = '#' + list.join('&');
      }
    };
  };
  myGoban = function($http, $sce, $gobanPath, $gobanTitle, $hash, $gobanMax, $timeout){
    var goban, parseFromCSV, res$, i$, ridx$, goX, goY;
    goban = new Object;
    parseFromCSV = function(csv){
      var allTextLines, bodyLines, goodList, lastFolder, bestList;
      allTextLines = csv.split(/\r\n|\n/);
      bodyLines = allTextLines.slice(2);
      goodList = bodyLines.map(function(text){
        return text.split(',');
      }).filter(function(list){
        return list[1];
      });
      lastFolder = {
        id: 0,
        set: function(n){
          this.id = n;
        }
      };
      bestList = goodList.map(function(list, index){
        var isClosed, obj;
        isClosed = false;
        if (!list[0]) {
          lastFolder.set(index);
          if (list[2] && list[2].search(/expand(.+)true/ > -1)) {
            isClosed = true;
          }
        }
        obj = (list[0] && {
          url: list[0].replace(/["\s]/g, ''),
          name: list[1].replace(/["\s]/g, ''),
          isFolder: false,
          pIndex: lastFolder.id
        }) || {
          name: list[1],
          isFolder: true,
          isClosed: isClosed
        };
        return obj;
      });
      return bestList;
    };
    goban.path = $gobanPath || '';
    goban.title = $hash.asArray()[0] || $gobanTitle;
    goban.myI = $hash.asArray()[1] || 0;
    goban.myJ = $hash.asArray()[2] || 0;
    goban.pageLoading = false;
    goban.animate = new Object;
    goban.colMax = $gobanMax || 3;
    res$ = [];
    for (i$ = 0; i$ <= $gobanMax; ++i$) {
      ridx$ = i$;
      res$.push(ridx$);
    }
    goban.myColumnIndex = res$;
    goban.setI = function(n){
      if (goban.myI !== n) {
        goban.loadPage();
        $timeout(function(){
          goban.myI = n;
          goban.updateHash();
          goban.load(goban.myI);
        }, 1000);
      }
    };
    goban.setJ = function(n){
      if (goban.myJ !== n) {
        goban.loadPage();
        $timeout(function(){
          goban.myJ = n;
          goban.updateHash();
        }, 1000);
      }
    };
    goban.loadPage = function(){
      goban.pageLoading = true;
      if (goban.animate.delay) {
        $timeout(function(){
          goban.pageLoading = false;
        }, goban.animate.delay);
      } else {
        goban.pageLoading = false;
      }
    };
    goban.updateHash = function(){
      $hash.upDateFromArray([goban.title, goban.myI, goban.myJ]);
    };
    goban.load = function(num){
      var folderName;
      folderName = $gobanTitle + num;
      if (typeof goban.folderNames === 'array') {
        folderName = goban.folderNames[num];
      }
      $http({
        method: "GET",
        url: $gobanPath + folderName + '.csv',
        dataType: "text"
      }).success(function(data){
        return goban.data = parseFromCSV(data);
      });
    };
    goban.keyDown = function($event){
      var code;
      console.log($event);
      $event.preventDefault();
      code = $event.keyCode;
      if (code === 40) {
        goban.dy(1);
      }
      if (code === 38) {
        goban.dy(-1);
      }
      if (code === 37) {
        goban.dx(-1);
      }
      if (code === 39) {
        goban.dx(1);
      }
      if (code === 32) {
        goban.data[goban.myJ].isClosed = !goban.data[goban.myJ].isClosed;
      }
    };
    goX = function(n){
      goban.myI = parseInt(goban.myI);
      goban.myI += n;
      if (goban.myI === -1) {
        goban.myI = goban.colMax;
      }
      if (goban.myI === goban.colMax + 1) {
        goban.myI = 0;
      }
      return goban.updateHash();
    };
    goY = function(n){
      goban.myJ = parseInt(goban.myJ);
      goban.myJ += n;
      if (goban.myJ === -1) {
        goban.myJ = goban.data.length - 1;
      }
      if (goban.myJ === goban.data.length) {
        goban.myJ = 0;
      }
      return goban.updateHash();
    };
    goban.dx = function(n){
      goban.loadPage();
      goban.load(parseInt(goban.myI) + n);
      if (goban.animate.delay) {
        $timeout(goX(n), goban.animate.delay);
      } else {
        goX(n);
      }
    };
    goban.dy = function(n){
      goban.loadPage();
      if (goban.animate.delay) {
        $timeout(goY(n), goban.animate.delay);
      } else {
        goY(n);
      }
    };
    goban.trust = function(url){
      return $sce.trustAsResourceUrl(url);
    };
    goban.getCurrentURL = function(){
      return goban.trust((goban.data[goban.myJ] && goban.data[goban.myJ].url) || (goban.data[goban.myJ + 1] && goban.data[goban.myJ + 1].url));
    };
    goban.backupAll = function(){
      var i$, ref$, len$, i;
      for (i$ = 0, len$ = (ref$ = (fn$())).length; i$ < len$; ++i$) {
        i = ref$[i$];
        window.open($gobanPath + $gobanTitle + i + '.csv', '_blank', "width=0, height=0, titlebar=no, toolbar=no");
      }
      function fn$(){
        var i$, to$, results$ = [];
        for (i$ = 0, to$ = $gobanMax; i$ <= to$; ++i$) {
          results$.push(i$);
        }
        return results$;
      }
    };
    return goban;
  };
  angular.module('goban', []).factory('$hash', myHash).factory('$goban', ['$http', '$sce', '$gobanPath', '$gobanTitle', '$hash', '$gobanMax', '$timeout', myGoban]).filter('toIndex', toIndex);
}).call(this);
